object Versions {
    const val CORE = "1.7.0"
    const val APPCOMPAT = "1.6.1"
    const val MATERIAL = "1.8.0"
    const val CONSTRAINTLAYOUT = "2.1.4"
    const val JUNIT = "4.13.2"
    const val EXT_JUNIT = "1.1.5"
    const val ESPRESSO = "3.5.1"
    const val RETROFIT = "2.9.0"
    const val DAGGER_HILT = "2.44"
    const val MOSHI = "1.14.0"
    const val INJECT = "1"
    const val LIFECYCLE = "2.5.1"
    const val NAVIGATION_COMPONENT = "2.5.3"
    const val GLIDE = "4.13.0"
    const val LIFECYCLE_VIEW_MODEL = "2.5.1"
    const val ROOM = "2.5.0"
    const val COROUTINES = "1.6.1"
}